"""WS2 localized-path audit oracles (round-2 plan; GH #455/#457 adjudication).

The localized programme is the manuscript's declared next step, and this
session's arc found four independent silent-wrongness defects on its path
(#445 basis, #444 deferred scale, #438 corner-collapse, #457
inter-constraint derivative mishandling). This module is the permanent
audit surface: every component of a localized run is pinned by an
EXACTNESS ORACLE — an independent computation of what the component must
produce, compared at machine precision — rather than end-to-end
comparisons that smear defects (the #367 lesson).

Core instrument: :class:`ResidualOracle`, an independent spec-driven
evaluator of the ORIGINAL equations on states generated by the built
operator. For the composed reduced operator ``A`` and recovery matrix
``R`` of path 4 (full-FFT basis, GH #445):

* dynamical q-rows:   dq/dt  = v                       (kinematic)
* dynamical v-rows:   M(x)·(dv/dt) − RHS_full(q, v, q_c, v_c, q̈) = 0
* constraint rows:    0 = Σ terms, INCLUDING the inter-constraint
  time-derivative terms that the builders mishandle (#457): with
  ``q_c = R·ŷ``, ``v_c = R·A·ŷ``, ``q̈ = (A²·ŷ)`` rows.

Everything on the right is evaluated with ~40 lines of independent numpy
(exact-k spectral operators, grid-evaluated coefficients) — no solver
internals are trusted beyond the operator under test itself.

Interpretation contract (GH #457): constraint-row residuals ≈ 0 along the
operator's flow ⇒ the Noether/Bianchi identities protect the truncation
on shell (recorded results safe; document). O(1) residuals on the rows
with mishandled terms ⇒ the truncation breaks the constraint manifold
and the DAE structure must be handled, consistently across paths 2 and 4.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from tidal.solver.coefficients import CoefficientEvaluator
from tidal.solver.grid import GridInfo
from tidal.solver.modal import (
    _build_convolution_matrix_with_constraints,
    _build_k_axes_full,
    _build_k_grid,
)
from tidal.solver.state import StateLayout
from tidal.symbolic.json_loader import ComponentEquation, EquationSystem, OperatorTerm

REPO_ROOT = Path(__file__).resolve().parent.parent

PHASE_E_PARAMS = {
    "kappa": 1.0,
    "Bpeak": 0.01,
    "sigB": 5.0,
    "zc1": 25.0,
    "zc2": 75.0,
}


# ---------------------------------------------------------------------------
# Independent spectral operator application (exact-k, full-FFT convention —
# matches the GH #445 basis of paths 3/4 by construction, derived here from
# first principles rather than imported from the solver).
# ---------------------------------------------------------------------------


def _spatial_apply(op: str, f_hat: np.ndarray, k: np.ndarray) -> np.ndarray:
    """Apply the SPATIAL part of ``op`` to a full-FFT spectrum (1-D)."""
    if op in {"identity", "first_derivative_t", "d2_t"}:
        return f_hat
    if op in {"gradient_x", "mixed_T1_S1x", "mixed_T2_S1x"}:
        return 1j * k * f_hat
    if op in {"laplacian", "laplacian_x"}:
        return -(k**2) * f_hat
    if op == "biharmonic":
        return (k**2) ** 2 * f_hat
    if op == "derivative_3_x":
        return -1j * k**3 * f_hat
    msg = f"oracle has no spatial rule for operator {op!r}"
    raise NotImplementedError(msg)


def _time_order(op: str) -> int:
    if op.startswith(("d2_t", "mixed_T2")):
        return 2
    if op.startswith(("first_derivative_t", "mixed_T1")):
        return 1
    return 0


class ResidualOracle:
    """Independent residual evaluation of a spec's ORIGINAL equations.

    Built for path 4 (grid states, full-FFT spectral derivatives). All
    coefficient evaluation goes through ``evaluate_coefficient`` on the
    grid's cell centers — the same public entry the time-domain backends
    use — never through the matrix builders under test.
    """

    def __init__(
        self,
        spec: EquationSystem,
        grid: GridInfo,
        params: dict[str, float],
    ) -> None:
        self.spec = spec
        self.grid = grid
        self.params = params
        self.n = grid.num_points
        length = grid.bounds[0][1] - grid.bounds[0][0]
        self.k = 2.0 * np.pi * np.fft.fftfreq(self.n, d=length / self.n)
        self.constraints = {
            eq.field_name for eq in spec.equations if eq.time_derivative_order == 0
        }

    # -- coefficient evaluation (independent path) ----------------------
    def _coeff(
        self, term: OperatorTerm, eq_idx: int, term_idx: int
    ) -> np.ndarray | float:
        from tidal.symbolic._eval_utils import evaluate_coefficient

        sym = term.coefficient_symbolic
        if sym is None:
            return float(term.coefficient)
        coords = [c for c in self.spec.effective_coordinates if c != "t"]
        coord_arrays = {c: self.grid.axes_coords(i) for i, c in enumerate(coords)}
        return evaluate_coefficient(
            sym, self.params, self.spec.effective_coordinates, coord_arrays, 0.0
        )

    def _kinetic(self, eq: ComponentEquation) -> np.ndarray | float:
        from tidal.symbolic._eval_utils import evaluate_coefficient

        sym = getattr(eq, "kinetic_coefficient_symbolic", None)
        if sym is None:
            return 1.0
        coords = [c for c in self.spec.effective_coordinates if c != "t"]
        coord_arrays = {c: self.grid.axes_coords(i) for i, c in enumerate(coords)}
        return evaluate_coefficient(
            sym, self.params, self.spec.effective_coordinates, coord_arrays, 0.0
        )

    # -- term-target resolution ------------------------------------------
    def _target_arrays(
        self,
        term: OperatorTerm,
        fields: dict[str, np.ndarray],
        vels: dict[str, np.ndarray],
        accels: dict[str, np.ndarray],
    ) -> np.ndarray | None:
        """Return the REAL-SPACE array the term's (time-resolved) target.

        ``fields``/``vels``/``accels`` map field name → real-space array for
        q, q̇, q̈ respectively (constraint entries included via recovery).
        Returns None when the required data is unavailable (reported by
        the caller as an oracle-coverage gap, never silently skipped).
        """
        tf = term.field
        is_vel = tf.startswith("v_")
        base = tf[2:] if is_vel else tf
        t_ord = _time_order(term.operator) + (1 if is_vel else 0)
        source = {0: fields, 1: vels, 2: accels}.get(t_ord)
        if source is None or base not in source:
            return None
        return source[base]

    # -- the oracle -------------------------------------------------------
    def residuals(
        self,
        fields: dict[str, np.ndarray],
        vels: dict[str, np.ndarray],
        accels: dict[str, np.ndarray],
        dv_dt: dict[str, np.ndarray],
    ) -> tuple[dict[str, float], dict[str, list[tuple[str, str]]]]:
        """Per-equation normalized max residuals + uncovered-term report.

        ``dv_dt`` maps dynamical field → dv/dt array (the operator's
        velocity-row action) for the LHS of dynamical rows.
        """
        out: dict[str, float] = {}
        gaps: dict[str, list[tuple[str, str]]] = {}
        for eq_idx, eq in enumerate(self.spec.equations):
            rhs = np.zeros(self.n)
            scale_norm = 0.0
            for term_idx, term in enumerate(eq.rhs_terms):
                tgt = self._target_arrays(term, fields, vels, accels)
                if tgt is None:
                    gaps.setdefault(eq.field_name, []).append(
                        (term.operator, term.field)
                    )
                    continue
                c = self._coeff(term, eq_idx, term_idx)
                contrib = np.fft.ifft(
                    _spatial_apply(term.operator, np.fft.fft(tgt), self.k)
                ).real
                contrib = np.asarray(c) * contrib
                rhs += contrib
                scale_norm = max(scale_norm, float(np.max(np.abs(contrib))))
            if eq.time_derivative_order >= 2:
                lhs = np.asarray(self._kinetic(eq)) * dv_dt[eq.field_name]
                res = lhs - rhs
                scale_norm = max(scale_norm, float(np.max(np.abs(lhs))))
            else:
                # constraint row: canonical form has everything on the RHS
                res = rhs
            out[eq.field_name] = float(np.max(np.abs(res))) / max(scale_norm, 1e-300)
        return out, gaps


# ---------------------------------------------------------------------------
# Path-4 operator fixture on a spec: build A/recovery, generate a random
# band-limited state, derive q_c / v_c / q̈ through the operator chain.
# ---------------------------------------------------------------------------


def _path4_state(
    spec: EquationSystem,
    grid: GridInfo,
    params: dict[str, float],
    seed: int = 457,
) -> dict[str, Any]:
    n = grid.num_points
    layout = StateLayout.from_spec(spec, n)
    ce = CoefficientEvaluator(spec, grid, params)
    k_grid = _build_k_grid(_build_k_axes_full(grid))
    A, recovery, c_names, o2r = _build_convolution_matrix_with_constraints(
        spec, layout, grid, ce, k_grid, tuple(grid.shape)
    )
    n_dyn = len(o2r)

    rng = np.random.default_rng(seed)
    k_int = np.fft.fftfreq(n, d=1.0 / n)
    keep = np.abs(k_int) <= 4
    y_hat = np.zeros(n_dyn * n, dtype=np.complex128)
    red_of: dict[str, dict[str, int]] = {"field": {}, "velocity": {}}
    for name, slot in layout.field_slot_map.items():
        if slot in o2r:
            red_of["field"][name] = o2r[slot]
    for name, slot in layout.velocity_slot_map.items():
        if slot in o2r:
            red_of["velocity"][name] = o2r[slot]
    for red in list(red_of["field"].values()) + list(red_of["velocity"].values()):
        spec_c = np.where(keep, rng.standard_normal(n) + 1j * rng.standard_normal(n), 0)
        real = np.fft.ifft(spec_c).real
        y_hat[red * n : (red + 1) * n] = np.fft.fft(real)

    Ay = A @ y_hat
    AAy = A @ Ay
    qc_hat = recovery @ y_hat
    vc_hat = recovery @ Ay
    ac_hat = recovery @ AAy

    def _r(vec: np.ndarray, idx: int) -> np.ndarray:
        return np.fft.ifft(vec[idx * n : (idx + 1) * n]).real

    fields = {nm: _r(y_hat, r) for nm, r in red_of["field"].items()}
    vels = {nm: _r(y_hat, r) for nm, r in red_of["velocity"].items()}
    # dv/dt and q̈ for dynamical fields: velocity rows of A·ŷ / A²·ŷ
    dv_dt = {nm: _r(Ay, r) for nm, r in red_of["velocity"].items()}
    accels = {nm: _r(Ay, r) for nm, r in red_of["velocity"].items()}
    for ci, cname in enumerate(c_names):
        fields[cname] = np.fft.ifft(qc_hat[ci * n : (ci + 1) * n]).real
        vels[cname] = np.fft.ifft(vc_hat[ci * n : (ci + 1) * n]).real
        accels[cname] = np.fft.ifft(ac_hat[ci * n : (ci + 1) * n]).real
    return {
        "fields": fields,
        "vels": vels,
        "accels": accels,
        "dv_dt": dv_dt,
        "c_names": c_names,
        "A": A,
    }


def _load(name: str) -> EquationSystem:
    p = REPO_ROOT / f"examples/data/{name}.json"
    if not p.exists():
        pytest.skip(f"{name}.json not present")
    return EquationSystem.from_dict(json.loads(p.read_text()))


# ---------------------------------------------------------------------------
# Oracles
# ---------------------------------------------------------------------------


def _synthetic_velc_spec() -> EquationSystem:
    """Positive control: the GH #444 synthetic (χ = h(x)·φ + deferred v_χ).

    No inter-constraint derivative terms, well-conditioned recovery — the
    oracle must close every row at machine precision here, guarding the
    oracle itself against rot independently of the #455/#457 pathology.
    """
    import sys

    sys.path.insert(0, str(REPO_ROOT / "tests"))
    from test_solver_constraint_posdep import _make_deferred_velc_spec

    return _make_deferred_velc_spec("1 + 0.25*Sin[x[]]", c_v=0.4)


class TestOraclePositiveControl:
    def test_synthetic_all_rows_close(self) -> None:
        spec = _synthetic_velc_spec()
        grid = GridInfo(bounds=((0.0, 2 * np.pi),), shape=(24,), periodic=(True,))
        params = {"alpha": 0.5}
        st = _path4_state(spec, grid, params)
        oracle = ResidualOracle(spec, grid, params)
        res, gaps = oracle.residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        assert not gaps, f"oracle coverage gaps on the control spec: {gaps}"
        bad = {k: v for k, v in res.items() if v > 1e-11}
        assert not bad, f"positive-control rows fail to close: {bad}"


class TestPath4ECalAdjudication:
    """GH #455/#457 adjudication on E.cal — MEASURED VERDICT (2026-08-25).

    Constraint rows h_0/h_1/h_2 (no mishandled terms): close at 1e-12–1e-15
    → recovery/Schur is machine-exact on the handled subspace.

    Full-closure xfails below carry the measured defect numbers:

    * constraint rows WITH dropped inter-constraint derivative terms:
      h_3 = 0.374, h_4 = 0.980, h_7 = 0.980, h_9 = 0.877 — the dropped
      terms are essentially the entire content of those rows. The
      Bianchi-identity-protection hypothesis is REFUTED for the truncated
      system; #457's truncation breaks the constraint manifold.
    * dynamical rows h_6 = 0.278, h_8 = 0.124 — numerical garbage from the
      near-singular velocity-coupling solve. Measured causal chain:
      truncated K_cc → ‖recovery‖ ≈ 1.2e6 → cond(B_lhs) ≈ 9.7e12 →
      the #455 operator explosion (abscissa 1594 @ N=16, 4977 @ N=24 —
      growing with resolution: a spurious operator, not physics).
    """

    def _state(self) -> tuple[EquationSystem, dict[str, Any], ResidualOracle]:
        spec = _load("gertsenshtein_ungauged_e_dual_gaussian")
        grid = GridInfo(bounds=((0.0, 100.0),), shape=(24,), periodic=(True,))
        st = _path4_state(spec, grid, PHASE_E_PARAMS)
        return spec, st, ResidualOracle(spec, grid, PHASE_E_PARAMS)

    def test_handled_subspace_certified(self) -> None:
        """Rows without mishandled terms MUST close — this is the strict,
        passing certification of the recovery/Schur chain for everything
        the builder claims to handle.
        """
        _spec, st, oracle = self._state()
        res, _gaps = oracle.residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        dropped_rows = {"h_3", "h_4", "h_7", "h_9"}
        vc_polluted = {"h_6", "h_8"}
        # a_2 sits at ~7e-9: conditioning residue of the near-singular
        # composition (cond ~1e13 loses ~13 digits); tolerance reflects
        # that measured floor, not a loosened contract.
        clean = {k: v for k, v in res.items() if k not in dropped_rows | vc_polluted}
        bad = {k: v for k, v in clean.items() if v > 1e-8}
        assert not bad, f"handled-subspace rows fail to close: {bad}"

    @pytest.mark.xfail(
        strict=True,
        reason="GH #457 CONFIRMED (measured 2026-08-25): dropped "
        "inter-constraint derivative terms leave O(1) residuals "
        "(h_3 0.374, h_4 0.980, h_7 0.980, h_9 0.877). Flips when the "
        "constraint sector's D_cc/M_cc structure is handled.",
    )
    def test_constraint_rows_full_closure(self) -> None:
        spec, st, oracle = self._state()
        res, _gaps = oracle.residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        con = {
            eq.field_name: res[eq.field_name]
            for eq in spec.equations
            if eq.time_derivative_order == 0
        }
        bad = {k: v for k, v in con.items() if v > 1e-8}
        assert not bad, f"constraint rows fail full closure: {bad}"

    @pytest.mark.xfail(
        strict=True,
        reason="GH #455 (measured 2026-08-25): near-singular "
        "velocity-coupling solve (cond(B_lhs) ≈ 9.7e12, driven by the "
        "#457-truncated K_cc's ‖recovery‖ ≈ 1.2e6) corrupts the "
        "VC-coupled velocity rows (h_6 0.278, h_8 0.124). Flips with the "
        "#457 fix.",
    )
    def test_dynamical_rows_full_closure(self) -> None:
        spec, st, oracle = self._state()
        res, _gaps = oracle.residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        dyn = {
            eq.field_name: res[eq.field_name]
            for eq in spec.equations
            if eq.time_derivative_order >= 2
        }
        bad = {k: v for k, v in dyn.items() if v > 1e-8}
        assert not bad, f"dynamical rows fail full closure: {bad}"
