"""WS2 localized-path audit oracles (round-2 plan; GH #455/#457 adjudication).

The localized programme is the manuscript's declared next step, and this
session's arc found four independent silent-wrongness defects on its path
(#445 basis, #444 deferred scale, #438 corner-collapse, #457
inter-constraint derivative mishandling). This module is the permanent
audit surface: every component of a localized run is pinned by an
EXACTNESS ORACLE — an independent computation of what the component must
produce, compared at machine precision — rather than end-to-end
comparisons that smear defects (the #367 lesson).

Core instrument: :class:`ResidualOracle`, an independent spec-driven
evaluator of the ORIGINAL equations on states generated by the built
operator. For the composed reduced operator ``A`` and recovery matrix
``R`` of path 4 (full-FFT basis, GH #445):

* dynamical q-rows:   dq/dt  = v                       (kinematic)
* dynamical v-rows:   M(x)·(dv/dt) − RHS_full(q, v, q_c, v_c, q̈) = 0
* constraint rows:    0 = Σ terms, INCLUDING the inter-constraint
  time-derivative terms that the builders mishandle (#457): with
  ``q_c = R·ŷ``, ``v_c = R·A·ŷ``, ``q̈ = (A²·ŷ)`` rows.

Everything on the right is evaluated with ~40 lines of independent numpy
(exact-k spectral operators, grid-evaluated coefficients) — no solver
internals are trusted beyond the operator under test itself.

Interpretation contract (GH #457): constraint-row residuals ≈ 0 along the
operator's flow ⇒ the Noether/Bianchi identities protect the truncation
on shell (recorded results safe; document). O(1) residuals on the rows
with mishandled terms ⇒ the truncation breaks the constraint manifold
and the DAE structure must be handled, consistently across paths 2 and 4.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from tidal.solver.coefficients import CoefficientEvaluator
from tidal.solver.grid import GridInfo
from tidal.solver.modal import (
    _build_convolution_matrix_with_constraints,
    _build_evolution_matrices,
    _build_k_axes,
    _build_k_axes_full,
    _build_k_grid,
)
from tidal.solver.state import StateLayout
from tidal.symbolic.json_loader import ComponentEquation, EquationSystem, OperatorTerm

REPO_ROOT = Path(__file__).resolve().parent.parent

PHASE_E_PARAMS = {
    "kappa": 1.0,
    "Bpeak": 0.01,
    "sigB": 5.0,
    "zc1": 25.0,
    "zc2": 75.0,
}


# ---------------------------------------------------------------------------
# Independent spectral operator application (exact-k, full-FFT convention —
# matches the GH #445 basis of paths 3/4 by construction, derived here from
# first principles rather than imported from the solver).
# ---------------------------------------------------------------------------


def _spatial_apply(op: str, f_hat: np.ndarray, k: np.ndarray) -> np.ndarray:
    """Apply the SPATIAL part of ``op`` to a full-FFT spectrum (1-D)."""
    if op in {"identity", "first_derivative_t", "d2_t"}:
        return f_hat
    if op in {"gradient_x", "mixed_T1_S1x", "mixed_T2_S1x"}:
        return 1j * k * f_hat
    if op in {"laplacian", "laplacian_x"}:
        return -(k**2) * f_hat
    if op == "biharmonic":
        return (k**2) ** 2 * f_hat
    if op == "derivative_3_x":
        return -1j * k**3 * f_hat
    msg = f"oracle has no spatial rule for operator {op!r}"
    raise NotImplementedError(msg)


def _time_order(op: str) -> int:
    if op.startswith(("d2_t", "mixed_T2")):
        return 2
    if op.startswith(("first_derivative_t", "mixed_T1")):
        return 1
    return 0


class ResidualOracle:
    """Independent residual evaluation of a spec's ORIGINAL equations.

    Built for path 4 (grid states, full-FFT spectral derivatives). All
    coefficient evaluation goes through ``evaluate_coefficient`` on the
    grid's cell centers — the same public entry the time-domain backends
    use — never through the matrix builders under test.
    """

    def __init__(
        self,
        spec: EquationSystem,
        grid: GridInfo,
        params: dict[str, float],
    ) -> None:
        self.spec = spec
        self.grid = grid
        self.params = params
        self.n = grid.num_points
        length = grid.bounds[0][1] - grid.bounds[0][0]
        self.k = 2.0 * np.pi * np.fft.fftfreq(self.n, d=length / self.n)
        self.constraints = {
            eq.field_name for eq in spec.equations if eq.time_derivative_order == 0
        }

    # -- coefficient evaluation (independent path) ----------------------
    def _coeff(
        self, term: OperatorTerm, eq_idx: int, term_idx: int
    ) -> np.ndarray | float:
        from tidal.symbolic._eval_utils import evaluate_coefficient

        sym = term.coefficient_symbolic
        if sym is None:
            return float(term.coefficient)
        coords = [c for c in self.spec.effective_coordinates if c != "t"]
        coord_arrays = {c: self.grid.axes_coords(i) for i, c in enumerate(coords)}
        return evaluate_coefficient(
            sym, self.params, self.spec.effective_coordinates, coord_arrays, 0.0
        )

    def _kinetic(self, eq: ComponentEquation) -> np.ndarray | float:
        from tidal.symbolic._eval_utils import evaluate_coefficient

        sym = getattr(eq, "kinetic_coefficient_symbolic", None)
        if sym is None:
            return 1.0
        coords = [c for c in self.spec.effective_coordinates if c != "t"]
        coord_arrays = {c: self.grid.axes_coords(i) for i, c in enumerate(coords)}
        return evaluate_coefficient(
            sym, self.params, self.spec.effective_coordinates, coord_arrays, 0.0
        )

    # -- term-target resolution ------------------------------------------
    def _target_arrays(
        self,
        term: OperatorTerm,
        fields: dict[str, np.ndarray],
        vels: dict[str, np.ndarray],
        accels: dict[str, np.ndarray],
    ) -> np.ndarray | None:
        """Return the REAL-SPACE array the term's (time-resolved) target.

        ``fields``/``vels``/``accels`` map field name → real-space array for
        q, q̇, q̈ respectively (constraint entries included via recovery).
        Returns None when the required data is unavailable (reported by
        the caller as an oracle-coverage gap, never silently skipped).
        """
        tf = term.field
        is_vel = tf.startswith("v_")
        base = tf[2:] if is_vel else tf
        t_ord = _time_order(term.operator) + (1 if is_vel else 0)
        source = {0: fields, 1: vels, 2: accels}.get(t_ord)
        if source is None or base not in source:
            return None
        return source[base]

    # -- the oracle -------------------------------------------------------
    def residuals(
        self,
        fields: dict[str, np.ndarray],
        vels: dict[str, np.ndarray],
        accels: dict[str, np.ndarray],
        dv_dt: dict[str, np.ndarray],
    ) -> tuple[dict[str, float], dict[str, list[tuple[str, str]]]]:
        """Per-equation normalized max residuals + uncovered-term report.

        ``dv_dt`` maps dynamical field → dv/dt array (the operator's
        velocity-row action) for the LHS of dynamical rows.
        """
        out: dict[str, float] = {}
        gaps: dict[str, list[tuple[str, str]]] = {}
        for eq_idx, eq in enumerate(self.spec.equations):
            rhs = np.zeros(self.n)
            scale_norm = 0.0
            for term_idx, term in enumerate(eq.rhs_terms):
                tgt = self._target_arrays(term, fields, vels, accels)
                if tgt is None:
                    gaps.setdefault(eq.field_name, []).append(
                        (term.operator, term.field)
                    )
                    continue
                c = self._coeff(term, eq_idx, term_idx)
                contrib = np.fft.ifft(
                    _spatial_apply(term.operator, np.fft.fft(tgt), self.k)
                ).real
                contrib = np.asarray(c) * contrib
                rhs += contrib
                scale_norm = max(scale_norm, float(np.max(np.abs(contrib))))
            if eq.time_derivative_order >= 2:
                lhs = np.asarray(self._kinetic(eq)) * dv_dt[eq.field_name]
                res = lhs - rhs
                scale_norm = max(scale_norm, float(np.max(np.abs(lhs))))
            else:
                # constraint row: canonical form has everything on the RHS
                res = rhs
            out[eq.field_name] = float(np.max(np.abs(res))) / max(scale_norm, 1e-300)
        return out, gaps


# ---------------------------------------------------------------------------
# Path-4 operator fixture on a spec: build A/recovery, generate a random
# band-limited state, derive q_c / v_c / q̈ through the operator chain.
# ---------------------------------------------------------------------------


def _path4_state(
    spec: EquationSystem,
    grid: GridInfo,
    params: dict[str, float],
    seed: int = 457,
) -> dict[str, Any]:
    n = grid.num_points
    layout = StateLayout.from_spec(spec, n)
    ce = CoefficientEvaluator(spec, grid, params)
    k_grid = _build_k_grid(_build_k_axes_full(grid))
    A, recovery, c_names, o2r, conv_proj = _build_convolution_matrix_with_constraints(
        spec, layout, grid, ce, k_grid, tuple(grid.shape)
    )
    n_dyn = len(o2r)

    rng = np.random.default_rng(seed)
    k_int = np.fft.fftfreq(n, d=1.0 / n)
    keep = np.abs(k_int) <= 4
    y_hat = np.zeros(n_dyn * n, dtype=np.complex128)
    red_of: dict[str, dict[str, int]] = {"field": {}, "velocity": {}}
    for name, slot in layout.field_slot_map.items():
        if slot in o2r:
            red_of["field"][name] = o2r[slot]
    for name, slot in layout.velocity_slot_map.items():
        if slot in o2r:
            red_of["velocity"][name] = o2r[slot]
    for red in list(red_of["field"].values()) + list(red_of["velocity"].values()):
        spec_c = np.where(keep, rng.standard_normal(n) + 1j * rng.standard_normal(n), 0)
        real = np.fft.ifft(spec_c).real
        y_hat[red * n : (red + 1) * n] = np.fft.fft(real)

    if conv_proj is not None:
        # Post-#457 the promoted sector is deflated; the operator's
        # contract holds on the constraint manifold (membership itself
        # verified by the constraint rows closing).
        y_hat = conv_proj @ y_hat

    Ay = A @ y_hat
    AAy = A @ Ay
    qc_hat = recovery @ y_hat
    vc_hat = recovery @ Ay
    ac_hat = recovery @ AAy

    def _r(vec: np.ndarray, idx: int) -> np.ndarray:
        return np.fft.ifft(vec[idx * n : (idx + 1) * n]).real

    fields = {nm: _r(y_hat, r) for nm, r in red_of["field"].items()}
    vels = {nm: _r(y_hat, r) for nm, r in red_of["velocity"].items()}
    # dv/dt and q̈ for dynamical fields: velocity rows of A·ŷ / A²·ŷ
    dv_dt = {nm: _r(Ay, r) for nm, r in red_of["velocity"].items()}
    accels = {nm: _r(Ay, r) for nm, r in red_of["velocity"].items()}
    for ci, cname in enumerate(c_names):
        fields[cname] = np.fft.ifft(qc_hat[ci * n : (ci + 1) * n]).real
        vels[cname] = np.fft.ifft(vc_hat[ci * n : (ci + 1) * n]).real
        accels[cname] = np.fft.ifft(ac_hat[ci * n : (ci + 1) * n]).real
    if conv_proj is not None:
        # GH #468 slots mode: constraint values are evolved slots; their
        # velocities/accelerations come from the generator's rows.
        for si, slot in enumerate(layout.slots):
            if slot.kind == "constraint" and si in o2r:
                red = o2r[si]
                vels[slot.field_name] = _r(Ay, red)
                accels[slot.field_name] = _r(AAy, red)
    return {
        "fields": fields,
        "vels": vels,
        "accels": accels,
        "dv_dt": dv_dt,
        "c_names": c_names,
        "A": A,
    }


def _load(name: str) -> EquationSystem:
    p = REPO_ROOT / f"examples/data/{name}.json"
    if not p.exists():
        pytest.skip(f"{name}.json not present")
    return EquationSystem.from_dict(json.loads(p.read_text()))


# ---------------------------------------------------------------------------
# Oracles
# ---------------------------------------------------------------------------


def _synthetic_velc_spec() -> EquationSystem:
    """Positive control: the GH #444 synthetic (χ = h(x)·φ + deferred v_χ).

    No inter-constraint derivative terms, well-conditioned recovery — the
    oracle must close every row at machine precision here, guarding the
    oracle itself against rot independently of the #455/#457 pathology.
    """
    import sys

    sys.path.insert(0, str(REPO_ROOT / "tests"))
    from test_solver_constraint_posdep import _make_deferred_velc_spec

    return _make_deferred_velc_spec("1 + 0.25*Sin[x[]]", c_v=0.4)


class TestOraclePositiveControl:
    def test_synthetic_all_rows_close(self) -> None:
        spec = _synthetic_velc_spec()
        grid = GridInfo(bounds=((0.0, 2 * np.pi),), shape=(24,), periodic=(True,))
        params = {"alpha": 0.5}
        st = _path4_state(spec, grid, params)
        oracle = ResidualOracle(spec, grid, params)
        res, gaps = oracle.residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        assert not gaps, f"oracle coverage gaps on the control spec: {gaps}"
        bad = {k: v for k, v in res.items() if v > 1e-11}
        assert not bad, f"positive-control rows fail to close: {bad}"


class TestPath4ECalAdjudication:
    """GH #455/#457 adjudication on E.cal — MEASURED VERDICT (2026-08-25).

    Constraint rows h_0/h_1/h_2 (no mishandled terms): close at 1e-12–1e-15
    → recovery/Schur is machine-exact on the handled subspace.

    Full-closure xfail marks below carry the measured defect numbers:

    * constraint rows WITH dropped inter-constraint derivative terms:
      h_3 = 0.374, h_4 = 0.980, h_7 = 0.980, h_9 = 0.877 — the dropped
      terms are essentially the entire content of those rows. The
      Bianchi-identity-protection hypothesis is REFUTED for the truncated
      system; #457's truncation breaks the constraint manifold.
    * dynamical rows h_6 = 0.278, h_8 = 0.124 — numerical garbage from the
      near-singular velocity-coupling solve. Measured causal chain:
      truncated K_cc → ‖recovery‖ ≈ 1.2e6 → cond(B_lhs) ≈ 9.7e12 →
      the #455 operator explosion (abscissa 1594 @ N=16, 4977 @ N=24 —
      growing with resolution: a spurious operator, not physics).
    """

    def _state(self) -> tuple[EquationSystem, dict[str, Any], ResidualOracle]:
        spec = _load("gertsenshtein_ungauged_e_dual_gaussian")
        grid = GridInfo(bounds=((0.0, 100.0),), shape=(24,), periodic=(True,))
        st = _path4_state(spec, grid, PHASE_E_PARAMS)
        return spec, st, ResidualOracle(spec, grid, PHASE_E_PARAMS)

    def test_promoted_localized_build_refuses_honestly(self) -> None:
        """GH #468: the corrected path-4 assembly for promoted localized
        specs REFUSES rather than silently evolving a wrong operator.

        History of this test: it originally certified the healthy
        subspace of the pre-#457 TRUNCATED operator (the one whose #455
        abscissa grew with resolution). That operator no longer exists —
        the promoted sector now assembles as a 528-dim coupled pencil
        whose float64 deflation is not yet robust (tolerance compounding;
        ‖A‖ ≈ 5.4e6 physical stiffness after the #459-mirrored pinv
        recovery). Until #468 lands the robust deflation, the honest
        behavior is a loud SingularPencilError with the breakdown
        diagnosis.
        """
        from tidal.solver.modal import SingularPencilError

        spec = _load("gertsenshtein_ungauged_e_dual_gaussian")
        grid = GridInfo(bounds=((0.0, 100.0),), shape=(24,), periodic=(True,))
        with pytest.raises(SingularPencilError):
            _path4_state(spec, grid, PHASE_E_PARAMS)

    def test_closure_restricted_ecal_full_closure(self) -> None:
        """GH #468 route 3 (2026-08-27): the exactly closed observable
        sector {h_5, a_1} evolves at machine precision through the
        certified non-promoted path-4 machinery.

        Re-scoped from two former strict xfails that awaited a float64
        operator for the FULL localized pencil. The Lane 1c experiment
        showed no such operator exists without the Kronecker-like
        staircase reduction (GH #474 root cause, #473 the general fix);
        what every reduction tried did reproduce was this decoupled
        block, at 1e-11..1e-15 — the closure contract is the meaningful
        gate for the observable that the Phase E campaign measures.
        """
        from tidal.symbolic.json_loader import restrict_spec_dict

        path = REPO_ROOT / "examples/data/gertsenshtein_ungauged_e_dual_gaussian.json"
        if not path.exists():
            pytest.skip("E.cal spec not present")
        data = json.loads(path.read_text())
        full = EquationSystem.from_dict(data)
        closure = full.dependency_closure({"h_5", "a_1"})
        assert closure == {"h_5", "a_1"}, f"closure moved: {sorted(closure)}"
        restricted, record = restrict_spec_dict(data, closure)
        assert record.omitted
        assert record.dropped_hamiltonian_terms > 0
        spec = EquationSystem.from_dict(restricted)
        assert not spec.second_order_sector.promoted
        grid = GridInfo(bounds=((0.0, 100.0),), shape=(24,), periodic=(True,))
        st = _path4_state(spec, grid, PHASE_E_PARAMS)
        res, gaps = ResidualOracle(spec, grid, PHASE_E_PARAMS).residuals(
            st["fields"], st["vels"], st["accels"], st["dv_dt"]
        )
        assert not gaps, f"oracle coverage gaps: {gaps}"
        bad = {k: v for k, v in res.items() if v > 1e-11}
        assert not bad, f"closure-restricted E.cal rows fail to close: {bad}"


# ---------------------------------------------------------------------------
# Per-mode PATH-2 oracle (uniform specs → _build_evolution_matrices).
#
# Stage-0 instrument of the hardened WS2/#457 plan: the constant-coefficient
# genEig path ran the UNIFORM thesis campaigns, so its constraint-row
# handling must be adjudicated with the same rigor as path 4's — but with an
# instrument whose own positive control passes first (the first scratch
# harness double-counted the mass matrix on dynamical rows and its numbers
# were discarded; that failure mode is pinned in PerModeOracle's docstring).
# ---------------------------------------------------------------------------


def _spatial_mult(op: str, k: float) -> complex:
    """Scalar spatial multiplier of ``op`` at wavenumber ``k`` (1-D)."""
    return complex(
        _spatial_apply(op, np.ones(1, dtype=np.complex128), np.array([k]))[0]
    )


def _uniform_velc_spec(kinetic: str | None, c_v: float = 0.4) -> EquationSystem:
    """Constant-coefficient variant of the GH #444 synthetic for path 2.

    φ with ``M·d2_t(φ) = ∂²ₓφ + c_v·v_χ`` and constraint ``χ = h·φ`` with
    CONSTANT ``h`` (path 2 is the constant-coefficient engine — the
    ``Cos[x[]]`` coupling of the path-4 control is out of its contract).
    Analytically ``v_χ = h·v_φ``, so the composed generator must satisfy
    ``dv_φ/dt = (1/M)·(−k²·φ + c_v·h·v_φ)`` per mode.
    """
    h_amp = 0.5
    spec_data: dict[str, Any] = {
        "metadata": {"name": "gh457_p2_synthetic", "parameters": {"alpha": 0.5}},
        "spacetime": {"dimension": 2, "signature": [-1, 1], "coordinates": ["t", "x"]},
        "fields": [{"name": "phi", "index": 0}, {"name": "chi", "index": 1}],
        "equations": [
            {
                "field": "phi",
                "lhs": {
                    "expression": "d2_t(phi)",
                    "order": {"time": 2, "space": 0},
                    **(
                        {"kinetic_coefficient_symbolic": kinetic}
                        if kinetic is not None
                        else {}
                    ),
                },
                "rhs": {
                    "type": "linear_combination",
                    "terms": [
                        {
                            "coefficient": 1.0,
                            "operator": "laplacian_x",
                            "field": "phi",
                        },
                        {
                            "coefficient": c_v,
                            "operator": "identity",
                            "field": "v_chi",
                        },
                    ],
                },
            },
            {
                "field": "chi",
                "lhs": {"expression": "chi", "order": {"time": 0, "space": 0}},
                "rhs": {
                    "type": "linear_combination",
                    "terms": [
                        {"coefficient": -1.0, "operator": "identity", "field": "chi"},
                        {"coefficient": h_amp, "operator": "identity", "field": "phi"},
                    ],
                },
            },
        ],
    }
    return EquationSystem.from_dict(spec_data)


class PerModeOracle:
    """Independent per-mode residual evaluation for UNIFORM specs (path 2).

    Verified path-2 semantics (GH #457 investigation, 2026-08-25):
    ``_build_evolution_matrices`` returns ``A_rhs`` whose velocity rows are
    ALREADY M⁻¹-scaled (batched ``m_inv @ K/D``), and ``B_lhs =
    I − A_dc_vel·recovery`` or ``None``; the per-mode evolution generator
    is ``G = B⁻¹·A`` (QZ generalized eig in production). The oracle must
    therefore NOT multiply the generator's velocity-row output by the mass
    matrix when forming q̈ — doing so double-counts M (the bug that
    invalidated the first scratch harness; its numbers were discarded).
    Row check is identical to :class:`ResidualOracle`:
    ``kinetic_i·q̈_i − Σ(independently evaluated terms) = 0`` for
    dynamical rows, ``Σ terms = 0`` for constraint rows.

    Modes whose ``cond(B)`` exceeds 1e10 are excluded from residual claims
    and counted in the diagnostics (a near-singular velocity-coupling
    solve is a separate finding — the #455 signature — not a residual
    measurement).

    Constraint rows with NO time-derivative reference to another
    constraint field close BY CONSTRUCTION (the recovery is defined by
    solving exactly those rows in S_cc/S_cd form) — they are listed in
    the diagnostics as ``by_construction`` so tautological closures are
    never quoted as evidence of health.
    """

    def __init__(
        self,
        spec: EquationSystem,
        grid: GridInfo,
        params: dict[str, float],
    ) -> None:
        if len(grid.shape) != 1:
            msg = "PerModeOracle currently supports 1-D grids only"
            raise NotImplementedError(msg)
        self.spec = spec
        self.grid = grid
        self.params = params
        self.layout = StateLayout.from_spec(spec, grid.num_points)
        ce = CoefficientEvaluator(spec, grid, params)
        k_axes = _build_k_axes(grid)
        k_grid = _build_k_grid(k_axes)
        rfft_shape_list = list(grid.shape)
        rfft_shape_list[-1] = grid.shape[-1] // 2 + 1
        rfft_shape = tuple(rfft_shape_list)
        (
            self.A_rhs,
            self.B_lhs,
            self.recovery,
            _v_rec,
            self.c_names,
            self.o2r,
            _scc_inv,
            _sing_mask,
            self.manifold_proj,
        ) = _build_evolution_matrices(spec, self.layout, grid, ce, k_grid, rfft_shape)
        self.k_flat = np.asarray(k_grid[0]).reshape(-1)
        self.n_dyn = self.A_rhs.shape[1]
        self.constraint_set = {
            eq.field_name for eq in spec.equations if eq.time_derivative_order == 0
        }

    # -- constant coefficient evaluation (independent path) ---------------
    def _const_scalar(self, sym: str | None, fallback: float) -> complex:
        from tidal.symbolic._eval_utils import evaluate_coefficient

        if sym is None:
            return complex(fallback)
        val = evaluate_coefficient(
            sym, self.params, self.spec.effective_coordinates, {}, 0.0
        )
        arr = np.asarray(val)
        if arr.ndim != 0:
            msg = f"coefficient {sym!r} is not constant — wrong oracle for this spec"
            raise ValueError(msg)
        return complex(arr)

    def _generator(self, m: int) -> tuple[np.ndarray, float]:
        A_m = self.A_rhs[m]
        if self.B_lhs is None:
            return A_m, 1.0
        B_m = self.B_lhs[m]
        cond = float(np.linalg.cond(B_m))
        if cond <= 1e10:
            return np.linalg.solve(B_m, A_m), cond
        return A_m, cond  # excluded by the caller; value unused

    def _row_is_by_construction(self, eq: ComponentEquation) -> bool:
        if eq.time_derivative_order != 0:
            return False
        for term in eq.rhs_terms:
            tf = term.field
            is_vel = tf.startswith("v_")
            base = tf[2:] if is_vel else tf
            if base in self.constraint_set and (
                is_vel or _time_order(term.operator) >= 1
            ):
                return False
        return True

    def _mode_state(
        self, m: int, y: np.ndarray, G: np.ndarray
    ) -> tuple[
        dict[str, complex], dict[str, complex], dict[str, complex], dict[str, complex]
    ]:
        """Per-mode scalar state dicts (fields, vels, accels, dv_dt)."""
        dy = G @ y
        d2y = G @ dy
        fields: dict[str, complex] = {}
        vels: dict[str, complex] = {}
        accels: dict[str, complex] = {}
        dv_dt: dict[str, complex] = {}
        for name, slot in self.layout.field_slot_map.items():
            if slot in self.o2r:
                fields[name] = complex(y[self.o2r[slot]])
        for name, slot in self.layout.velocity_slot_map.items():
            if slot in self.o2r:
                red = self.o2r[slot]
                vels[name] = complex(y[red])
                dv_dt[name] = complex(dy[red])
                accels[name] = complex(dy[red])
        qc = self.recovery[m] @ y
        vc = self.recovery[m] @ dy
        ac = self.recovery[m] @ d2y
        for ci, cname in enumerate(self.c_names):
            fields[cname] = complex(qc[ci])
            vels[cname] = complex(vc[ci])
            accels[cname] = complex(ac[ci])
        return fields, vels, accels, dv_dt

    def _row_residual(
        self,
        eq: ComponentEquation,
        k: float,
        state: tuple[
            dict[str, complex],
            dict[str, complex],
            dict[str, complex],
            dict[str, complex],
        ],
        gaps: dict[str, list[tuple[str, str]]],
    ) -> float:
        fields, vels, accels, dv_dt = state
        rhs = 0.0 + 0.0j
        scale = 0.0
        for term in eq.rhs_terms:
            tf = term.field
            is_vel = tf.startswith("v_")
            base = tf[2:] if is_vel else tf
            t_ord = _time_order(term.operator) + (1 if is_vel else 0)
            source = {0: fields, 1: vels, 2: accels}.get(t_ord)
            if source is None or base not in source:
                entry = (term.operator, term.field)
                if entry not in gaps.setdefault(eq.field_name, []):
                    gaps[eq.field_name].append(entry)
                continue
            c = self._const_scalar(term.coefficient_symbolic, float(term.coefficient))
            contrib = c * _spatial_mult(term.operator, k) * source[base]
            rhs += contrib
            scale = max(scale, abs(contrib))
        if eq.time_derivative_order >= 2:
            kin = self._const_scalar(
                getattr(eq, "kinetic_coefficient_symbolic", None), 1.0
            )
            lhs = kin * dv_dt[eq.field_name]
            res = lhs - rhs
            scale = max(scale, abs(lhs))
        else:
            res = rhs
        return abs(res) / max(scale, 1e-300)

    # -- the oracle -------------------------------------------------------
    def residuals(
        self, seed: int = 4577
    ) -> tuple[dict[str, float], dict[str, list[tuple[str, str]]], dict[str, Any]]:
        """Per-row max normalized residual over all well-posed modes.

        Returns ``(rows, gaps, diag)``: residuals keyed by equation,
        coverage gaps (term targets the oracle could not resolve — never
        silently skipped), and diagnostics (excluded ill-conditioned
        modes, max cond(B), by-construction row list).
        """
        rng = np.random.default_rng(seed)
        rows: dict[str, float] = {}
        gaps: dict[str, list[tuple[str, str]]] = {}
        diag: dict[str, Any] = {
            "excluded_modes": 0,
            "max_cond_B": 1.0,
            "by_construction": sorted(
                eq.field_name
                for eq in self.spec.equations
                if self._row_is_by_construction(eq)
            ),
        }
        for m in range(self.k_flat.size):
            k = float(self.k_flat[m])
            G, cond = self._generator(m)
            diag["max_cond_B"] = max(diag["max_cond_B"], cond)
            if cond > 1e10:
                diag["excluded_modes"] += 1
                continue
            y = rng.standard_normal(self.n_dyn) + 1j * rng.standard_normal(self.n_dyn)
            if self.manifold_proj is not None:
                # Post-#457 builders reduce to the constraint manifold;
                # the operator's contract holds ON it. Manifold membership
                # is itself verified by the constraint rows closing.
                y = self.manifold_proj[m] @ y
            state = self._mode_state(m, y, G)
            for eq in self.spec.equations:
                r_norm = self._row_residual(eq, k, state, gaps)
                rows[eq.field_name] = max(rows.get(eq.field_name, 0.0), r_norm)
        return rows, gaps, diag


class TestPath2PerModeOracle:
    """Positive control for the Stage-0 path-2 instrument.

    The oracle itself must be proven before any of its numbers count as
    evidence (WS2 lessons register: the first scratch harness failed its
    would-be control by double-counting M). With unit mass the composed
    generator has no M⁻¹ ambiguity anywhere, and every row must close at
    machine precision.
    """

    def test_positive_control_unit_mass(self) -> None:
        spec = _uniform_velc_spec(None)
        grid = GridInfo(bounds=((0.0, 2 * np.pi),), shape=(24,), periodic=(True,))
        oracle = PerModeOracle(spec, grid, {"alpha": 0.5})
        rows, gaps, diag = oracle.residuals()
        assert not gaps, f"oracle coverage gaps on the control spec: {gaps}"
        assert diag["excluded_modes"] == 0
        bad = {name: v for name, v in rows.items() if v > 1e-11}
        assert not bad, f"path-2 positive control fails to close: {bad}"

    def test_constraint_coupling_carries_row_mass_scale(self) -> None:
        """GH #458 mechanism 1 — FIXED by the pencil composition (2026-08-25).

        Pre-fix this was a strict xfail carrying the measured defect:
        A_dc emitted raw with no M⁻¹ gave residual exactly (M−1)/M = 1/3
        at M = 1.5. The pencil carries the row mass on the B side, so the
        fold-in is scale-correct by construction; this row now closes at
        machine precision and the test guards the fix permanently.
        """
        spec = _uniform_velc_spec("1 + alpha")  # M = 1.5, everything else equal
        grid = GridInfo(bounds=((0.0, 2 * np.pi),), shape=(24,), periodic=(True,))
        oracle = PerModeOracle(spec, grid, {"alpha": 0.5})
        rows, gaps, _diag = oracle.residuals()
        assert not gaps
        bad = {name: v for name, v in rows.items() if v > 1e-11}
        assert not bad, f"A_dc coupling misses the row mass scale: {bad}"


class TestPath2UniformProductionAdjudication:
    """Path-2 residuals on UNIFORM production specs (measured 2026-08-25).

    The constant-coefficient genEig path ran the uniform campaigns, so
    these are thesis-relevant numbers. All measured with the hardened
    per-mode oracle AFTER its positive control passed; cond(B) ≤ 4 on
    every mode of both specs, so none of this is conditioning garbage —
    every failure is structural. Mechanism attribution (verified against
    modal.py source, 2026-08-25):

    ``gertsenshtein_ungauged`` (κ=1, B0=0.01 — E.cal's uniform parent):

    * clean at ≤1e-8: a_0, a_1, h_5 (dynamical), h_0/h_1/h_2
      (recovery-defining, close by construction);
    * constraint rows h_4 2.027 / h_7 2.027 / h_9 2.326 — d2_t(C) folded
      into S_cc with spatial mult ≡ 1 (ḧᶜ treated as hᶜ, :1015-1017), and
      h_3 1.290 — gradient_x(v_C) silently falls through every branch of
      the constraint-row dispatch (:1018-1038). GH #457 on path 2.
    * dynamical rows h_6 1.006 / h_8 2.000 — A_dc_vel missing the row's
      M⁻¹ = −κ² (kinetic −κ⁻²: the missing factor is a SIGN FLIP);
      a_2 1.077 / a_3 0.982 — first_derivative_t(C) on a dynamical row
      matches ``target_field in c_idx_map`` FIRST (:1063-1066), so ḣᶜ is
      folded into A_dc_field as hᶜ — the t_order-blind dynamical-row
      analog of #457. a_3 has M = 1 and no other coupling: it isolates
      the t_order-blindness from the missing-M⁻¹ defect. NOTE: h_2 is
      NOT in the #457 promoted closure, so the reclassification alone
      does not fix a_3 — the A_dc dispatch itself needs t_order
      awareness.

    ``torsion_gertsenshtein`` base spec (b5-demoted) fails identically on
    the shared h/a sector (same eight rows, same numbers) — its ε⁰
    content coincides with the ungauged spec, cross-checking both runs.

    ``dark_photon_plasma`` (headline thesis theory; TEST params
    B0=0.01, alpha3=0.01, deltam=0.05, kappa=1, mA2=0.02, xi=1 — row
    structure is parameter-independent, magnitudes are not):

    * t_6/t_13/t_20 are BYTE-IDENTICAL constraint rows → S_cc is rank-1
      (exactly singular) at EVERY mode → the det-gated 1e-14 Tikhonov
      shift (:1476-1484) fires everywhere and its ill-conditioned inverse
      leaves 1e-4..1e-2 noise on rows that should close by construction;
    * dynamical rows t_2/t_10/t_17 1.35 (kinetic −ξ: A_dc_vel missing
      M⁻¹) and a_3 0.195 (M = 1; degenerate-recovery noise through its
      2·deltam·v_C couplings).
    """

    N = 24

    def _run(
        self, name: str, params: dict[str, float]
    ) -> tuple[dict[str, float], dict[str, Any]]:
        spec = _load(name)
        grid = GridInfo(bounds=((0.0, 100.0),), shape=(self.N,), periodic=(True,))
        oracle = PerModeOracle(spec, grid, params)
        rows, gaps, diag = oracle.residuals()
        assert not gaps, f"oracle coverage gaps on {name}: {gaps}"
        return rows, diag

    UNGAUGED_PARAMS = {"kappa": 1.0, "B0": 0.01}
    DPP_PARAMS = {
        "kappa": 1.0,
        "B0": 0.01,
        "alpha3": 0.01,
        "deltam": 0.05,
        "mA2": 0.02,
        "xi": 1.0,
    }

    def test_ungauged_handled_rows_certified(self) -> None:
        rows, diag = self._run("gertsenshtein_ungauged", self.UNGAUGED_PARAMS)
        assert diag["excluded_modes"] == 0
        assert diag["by_construction"] == ["h_0", "h_1", "h_2"]
        healthy = {"a_0", "a_1", "h_5", "h_0", "h_1", "h_2"}
        bad = {k: v for k, v in rows.items() if k in healthy and v > 1e-8}
        assert not bad, f"handled rows fail to close: {bad}"

    def test_ungauged_constraint_rows_full_closure(self) -> None:
        """GH #457 on path 2 — FIXED by promotion + the pencil engine.

        Pre-fix (strict xfail, measured 2026-08-25): h_3 1.290 / h_4 2.027
        / h_7 2.027 / h_9 2.326 — d2_t(C) folded into S_cc as identity,
        gradient_x(v_C) silently dropped. The promoted rows now live in
        the dynamical sector's pencil and close at machine precision.
        """
        rows, _diag = self._run("gertsenshtein_ungauged", self.UNGAUGED_PARAMS)
        con = {k: v for k, v in rows.items() if k in {"h_3", "h_4", "h_7", "h_9"}}
        bad = {k: v for k, v in con.items() if v > 1e-8}
        assert not bad, f"constraint rows fail full closure: {bad}"

    def test_ungauged_dynamical_rows_full_closure(self) -> None:
        """GH #458 both mechanisms — FIXED (t_order-aware A_dc + pencil).

        Pre-fix (strict xfail, measured 2026-08-25): h_6 1.006 / h_8 2.000
        (A_dc_vel missing M⁻¹ = −κ², a sign flip) and a_2 1.077 / a_3
        0.982 (t_order-blind fold of first_derivative_t(C) into
        A_dc_field). All four rows now close at machine precision.
        """
        rows, _diag = self._run("gertsenshtein_ungauged", self.UNGAUGED_PARAMS)
        dyn = {k: v for k, v in rows.items() if k in {"h_6", "h_8", "a_2", "a_3"}}
        bad = {k: v for k, v in dyn.items() if v > 1e-8}
        assert not bad, f"dynamical rows fail full closure: {bad}"

    def test_dark_photon_handled_rows_certified(self) -> None:
        """All DYNAMICAL rows now close at machine precision (2026-08-25).

        Pre-fix: t_2/t_10/t_17 at 1.35 (missing M⁻¹ on the −ξ rows) and
        a_3 at 0.195. The spec's byte-identical equation triplets
        (GH #465) make the pencil structurally singular at every mode;
        the engine's gauge completion drops the redundant combinations
        with a warning and the physical (sum) sector evolves exactly.
        """
        with pytest.warns(UserWarning, match="quotiented out"):
            rows, diag = self._run("dark_photon_plasma", self.DPP_PARAMS)
        assert diag["excluded_modes"] == 0
        healthy = {
            "a_0",
            "a_1",
            "a_2",
            "a_3",
            "h_5",
            "h_7",
            "t_0",
            "t_1",
            "t_2",
            "t_9",
            "t_10",
            "t_15",
            "t_17",
            "t_22",
            "t_23",
        }
        bad = {k: v for k, v in rows.items() if k in healthy and v > 1e-8}
        assert not bad, f"handled rows fail to close: {bad}"

    def test_dark_photon_full_closure(self) -> None:
        """GH #459 — FIXED (rank-revealing pinv residual elimination).

        Pre-fix (strict xfail): the rank-1 S_cc triplet t_6/t_13/t_20
        carried det-gated Tikhonov recovery noise (1.17e-2 at test
        params). With the pseudoinverse (min-norm on the consistent
        redundant system) EVERY row of the spec closes at machine
        precision.
        """
        with pytest.warns(UserWarning, match="quotiented out"):
            rows, _diag = self._run("dark_photon_plasma", self.DPP_PARAMS)
        bad = {k: v for k, v in rows.items() if v > 1e-8}
        assert not bad, f"rows fail full closure: {bad}"


class TestPath2NonminimalAdjudication:
    """RESOLVED diagnosis (GH #467, 2026-08-25): the T4 point is near
    constraint-index breakdown, not an assembly defect.

    Evidence chain: at delta1 = 0 or small couplings (0.1-scale) the
    assembled operator closes at ≤1e-10 (assembly is linear-correct);
    at the T4 point (delta1 = 1, alpha2 = −1) the pencil contains a
    GENUINE finite eigenvalue Re(λ) ≈ 2.3e8 (homogeneous residual
    6.5e-18) beyond the float64 conditioning horizon — keeping it
    poisons the composed operator by eps·|λ| = O(1) (oracle-refuted at
    O(0.03-1.8)), and zeroing it violates the equations at O(1)
    (also oracle-refuted, identically under two classifiers). The
    engine now REFUSES such points with the diagnosis; the stability
    probe converts the refusal to an honest "not simulatable as posed"
    verdict.
    """

    T4_PARAMS = {
        "kappa": 1.0,
        "B0": 0.01,
        "alpha1": 0.0,
        "alpha2": -1.0,
        "alpha3": 1.0,
        "delta1": 1.0,
    }
    SMALL_PARAMS = {
        "kappa": 1.0,
        "B0": 0.01,
        "alpha1": 0.0,
        "alpha2": -0.1,
        "alpha3": 0.1,
        "delta1": 0.1,
    }

    def test_small_coupling_point_closes(self) -> None:
        spec = _load("torsion_gertsenshtein_nonminimal")
        grid = GridInfo(bounds=((0.0, 50.0),), shape=(16,), periodic=(True,))
        oracle = PerModeOracle(spec, grid, self.SMALL_PARAMS)
        rows, gaps, _diag = oracle.residuals()
        assert not gaps
        bad = {k: v for k, v in rows.items() if v > 1e-8}
        assert not bad, f"rows fail closure: {bad}"

    def test_t4_point_closes_under_adaptive_floor(self) -> None:
        """The T4 near-breakdown point is RESOLVED by the adaptive
        determination floor (measured 2026-08-26, worst 4.0e-11).

        History: the fixed-tolerance engine refused this point (its
        genuine Re(λ) ≈ 2.3e8 mode could neither be kept — eps·|λ| = O(1)
        pollution — nor classifier-zeroed — O(1) equation violation).
        The adaptive floor instead QUOTIENTS the near-breakdown direction
        at a raised τ: a null-space quotient is equation-consistent at
        the τ level (unlike classifier zeroing), the deflation contract
        certifies the retained sector, and the oracle certifies the
        result end to end.
        """
        spec = _load("torsion_gertsenshtein_nonminimal")
        grid = GridInfo(bounds=((0.0, 50.0),), shape=(16,), periodic=(True,))
        with pytest.warns(UserWarning, match="determination floor"):
            oracle = PerModeOracle(spec, grid, self.T4_PARAMS)
        rows, gaps, _diag = oracle.residuals()
        assert not gaps
        bad = {k: v for k, v in rows.items() if v > 1e-8}
        assert not bad, f"T4 rows fail closure: {bad}"
