#!/usr/bin/env bash
# Monte Carlo Parameter Sweep: Dark Photon Torsion Model
#
# Sweeps over 3 coupling constants (alpha, xi, deltam) using Latin Hypercube
# sampling with arctan parameterisation to cover (-∞, +∞) uniformly.
#
# Physics:
#   L = (1/κ²)R̃ + α(I₁+I₂+I₃) - ¼ξ Ftorsion² + δ F·Ftorsion - ¼F²
#
#   alpha = unified torsion mass (β₁=β₂=β₃)
#   xi = torsion kinetic strength (ξ=1 = Maxwell strength)
#   deltam = EM-torsion kinetic mixing
#
# Ghost-freedom conditions (in our convention):
#   ξ > 0, α > 0, |δ|² < f(α, ξ)
#   The sweep samples ALL signs to map both physical and unphysical regions.
#
# Arctan parameterisation: x = tan(θ), θ ∈ (-π/2+ε, π/2-ε)
#   Uniformly samples (-∞, +∞) including sign transitions through zero.
#   Implemented via explicit values generated by a Python helper.
#
# Barker convention mapping:
#   ξ_ours = ξ_Barker/36, δ_ours = χ_Barker/6, α = β₁ = β₂ = β₃
#
# Refs:
#   Barker et al. (2406.12826) — eWGT completion, propagating vector torsion
#   Blagojević & Cvetković (1812.02675) — ghost/tachyon-free parameter windows

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SPEC="${SCRIPT_DIR}/../data/torsion_dark_photon.json"
OUTPUT="${SCRIPT_DIR}/../data/torsion_dark_photon_mc"

# Number of Monte Carlo samples
N_SAMPLES="${1:-100}"

# Fixed physics parameters
KAPPA=1.0
B0=0.01        # small-P regime (C = P/B₀² converges)
K0=2.0         # GW frequency (plane-wave wavevector)

# Grid and simulation settings
GRID=256
BOUNDS="0:100"
T_END=50.0

# Generate arctan-mapped sweep values for each parameter
# θ ∈ (-π/2+0.05, π/2-0.05) → x = tan(θ) ∈ (~-30, ~+30)
# Two values define the bounds for Latin Hypercube sampling
ALPHA_BOUNDS="-30:30:2"
XI_BOUNDS="-30:30:2"
DELTA_BOUNDS="-30:30:2"

echo "=== Dark Photon Torsion: Monte Carlo Sweep ==="
echo "Samples: ${N_SAMPLES}"
echo "Fixed: kappa=${KAPPA}, B0=${B0}, k0=${K0}"
echo "Output: ${OUTPUT}"
echo ""

uv run tidal sweep "${SPEC}" \
  --sweep "alpha=${ALPHA_BOUNDS}" \
  --sweep "xi=${XI_BOUNDS}" \
  --sweep "deltam=${DELTA_BOUNDS}" \
  --sweep-strategy latin_hypercube \
  --n-samples "${N_SAMPLES}" \
  --measure conversion,peak_conversion,conservation \
  --source h_7 --target a_2 \
  --grid-shape "${GRID}" --bounds "${BOUNDS}" --periodic \
  --ic plane-wave --ic-wavevector "${K0}" --ic-amplitude 0.1 --ic-component h_7 \
  --t-end "${T_END}" \
  --param "kappa=${KAPPA}" --param "B0=${B0}" \
  --parallel 4 --resume \
  --output "${OUTPUT}"

echo ""
echo "=== Sweep complete ==="
echo "Results: ${OUTPUT}"
echo ""
echo "Post-analysis:"
echo "  uv run tidal analyze ${OUTPUT} --sensitivity morris --metric P_max"
echo ""
echo "Conversion coefficient: C₀ = P_max / B₀² = P_max / ${B0}²"
echo "Amplification: A = √(C₀ / C₀_EM) relative to δ=ξ=0 baseline"
