#!/usr/bin/env bash
# Monte Carlo Parameter Sweep: Dark Photon Torsion Model
#
# Sweeps over 3 coupling constants (alpha, xi, deltam) using Latin Hypercube
# sampling with arctan parameterisation to cover (-∞, +∞) uniformly.
#
# Physics:
#   L = (1/κ²)R̃ + α I₃ - ¼ξ Ftorsion² + δ F·Ftorsion - ¼F²
#
# NOTE: Only the trace-sector torsion mass I₃ is included (not I₁+I₂+I₃).
# Including I₁/I₂ would add mass to tentor/trator sectors without kinetic terms
# → ghost instability. Only T_μ (trace) is made dynamical by ξ Ftorsion².
#
#   alpha = unified torsion mass (β₁=β₂=β₃)
#   xi = torsion kinetic strength (ξ=1 = Maxwell strength)
#   deltam = EM-torsion kinetic mixing
#
# Ghost-freedom conditions (in our convention):
#   ξ > 0, α > 0, |δ|² < f(α, ξ)
#   The sweep samples ALL signs to map both physical and unphysical regions.
#
# Arctan parameterisation: x = tan(θ), θ ∈ (-π/2+ε, π/2-ε)
#   Uniformly samples (-∞, +∞) including sign transitions through zero.
#   Implemented via explicit values generated by a Python helper.
#
# Barker convention mapping:
#   ξ_ours = ξ_Barker/36, δ_ours = χ_Barker/6, α = β₁ = β₂ = β₃
#
# Refs:
#   Barker et al. (2406.12826) — eWGT completion, propagating vector torsion
#   Blagojević & Cvetković (1812.02675) — ghost/tachyon-free parameter windows

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SPEC="${SCRIPT_DIR}/../data/torsion_dark_photon.json"
OUTPUT="${SCRIPT_DIR}/../data/torsion_dark_photon_mc"

# Number of Monte Carlo samples
N_SAMPLES="${1:-200}"

# Fixed physics parameters
KAPPA=1.0
B0=0.01        # small-P regime (C = P/B₀² converges)
K0=2.0         # GW frequency (plane-wave wavevector)

# Grid and simulation settings
GRID=256
BOUNDS="0:100"
T_END=50.0

# Generate arctan-mapped sweep values for each parameter
# θ ∈ (-π/2+0.05, π/2-0.05) → x = tan(θ) ∈ (~-30, ~+30)
# Two values define the bounds for Latin Hypercube sampling
ALPHA_BOUNDS="-30:30:2"
XI_BOUNDS="-30:30:2"
DELTA_BOUNDS="-30:30:2"

echo "=== Dark Photon Torsion: Monte Carlo Sweep ==="
echo "Samples: ${N_SAMPLES}"
echo "Fixed: kappa=${KAPPA}, B0=${B0}, k0=${K0}"
echo "Output: ${OUTPUT}"
echo ""

# NOTE: --measure conversion,peak_conversion only (no conservation).
# The total Hamiltonian is NOT a valid conservation check for this model.
# Dirac-Bergmann analysis: the gauge and constraint fields (a_0, a_3,
# unphysical h and t components) are not independent DOFs. Their contributions
# to the Hamiltonian are spurious — the constrained Hamiltonian is only
# well-defined on the physical h_5↔a_1 sector. Use P(t) from conversion
# as the primary quality metric. Diverged runs show up as P_max >> P_Gertsenshtein.
uv run tidal sweep "${SPEC}" \
  --sweep "alpha=${ALPHA_BOUNDS}" \
  --sweep "xi=${XI_BOUNDS}" \
  --sweep "deltam=${DELTA_BOUNDS}" \
  --sweep-strategy latin_hypercube \
  --n-samples "${N_SAMPLES}" \
  --measure conversion,peak_conversion \
  --source h_5 --target a_1 \
  --grid-shape "${GRID}" --bounds "${BOUNDS}" --periodic \
  --ic plane-wave --ic-wavevector "${K0}" --ic-amplitude 0.1 --ic-component h_5 \
  --t-end "${T_END}" \
  --param "kappa=${KAPPA}" --param "B0=${B0}" \
  --parallel 4 --no-require-stable --resume \
  --output "${OUTPUT}"
# --no-require-stable: R-tilde tensor/axial torsion sectors have tachyonic mass
# eigenvalues, but these modes have ZERO physical coupling (100% trace-aligned).
# The modal solver's _suppress_tachyonic_noise() (#222) freezes them.
# Some parameter combinations (alpha > 0.917 at xi=0.1) are genuinely unstable
# — these will be flagged as diverged in the output.

echo ""
echo "--- Generating plots ---"

# Sensitivity: which of (alpha, xi, deltam) drives conversion?
uv run tidal plot "${OUTPUT}" --type sweep-tornado \
  --metric P_max \
  --title "Dark photon torsion: parameter sensitivity (P_max)" \
  --output "${OUTPUT}/plot_tornado.png" --quiet

# Scatter matrix: all parameter pairs coloured by P_max
uv run tidal plot "${OUTPUT}" --type sweep-scatter \
  --metric P_max \
  --title "Dark photon torsion: parameter space (coloured by P_max)" \
  --output "${OUTPUT}/plot_scatter.png" --quiet

# C₀ = P/B₀² analysis with arctan-mapped scatter plots
# Shows relative amplification (C₀ - C_EM)/C_EM in percent
uv run python "${SCRIPT_DIR}/analyze_sweep.py" "${OUTPUT}"

# Parallel coordinates: multi-parameter trends
uv run tidal plot "${OUTPUT}" --type sweep-parallel \
  --metric P_max \
  --title "Dark photon torsion: parallel coordinates (P_max)" \
  --output "${OUTPUT}/plot_parallel.png" --quiet

echo ""
echo "=== Sweep complete ==="
echo "Results: ${OUTPUT}"
echo "Plots:"
echo "  ${OUTPUT}/plot_tornado.png   [parameter sensitivity ranking]"
echo "  ${OUTPUT}/plot_scatter.png   [pairwise scatter, coloured by P_max]"
echo "  ${OUTPUT}/plot_parallel.png  [parallel coordinates]"
echo "  ${OUTPUT}/analysis_C0.png    [C₀ relative deviation with arctan axes]"
echo ""
echo "Sensitivity analysis:"
echo "  uv run tidal analyze ${OUTPUT} --sensitivity morris --metric P_max"
echo ""
echo "Physics note (adiabatic decoupling):"
echo "  R-tilde mass floor: m_T >= sqrt(55) ~ 7.4 (from contorsion)"
echo "  Gertsenshtein frequency: omega_G = kappa*B0/2 = ${KAPPA}*${B0}/2"
echo "  Expected correction: dP/P ~ delta^2 * (omega_G/m_T)^2 ~ 5e-9"
