#!/usr/bin/env bash
# Massive 3-Form 3+1D — Full derive → inspect → simulate pipeline
#
# Antisymmetric rank-3 tensor: 64 components reduce to 4 independent (C_0..C_3)
# via epsilon symmetry. Each component satisfies a massive Klein-Gordon equation.
#
# NOTE: 3D spatial plots are auto-generated by tidal simulate (z-profile, xy-slice,
# amplitude decay, component independence). Use tidal plot for 1D/2D data only.
#
# To run manually:  cd examples/massive_3form && tidal derive theory.toml

set -euo pipefail
cd "$(dirname "$0")"

# Derive equations from Lagrangian (requires wolframscript)
tidal derive theory.toml

# Inspect the equation system
tidal inspect ../data/massive_3form.json

# Run simulation (Gaussian pulse in C_0, other components start at zero)
tidal simulate ../data/massive_3form.json \
  --param m2=1.0 \
  --grid-shape 16 \
  --bounds 0:10 \
  --periodic \
  --ic gaussian \
  --ic-component C_0 \
  --ic-width 1.5 \
  --t-end 5.0 \
  --scheme scipy
