r"""Generate Appendix-E equation/constraint/term counts as a TeX sidecar.

Walks the eight `manuscript/sections/appendices/listings/eom_<tag>_full.tex`
files and emits
`manuscript/sections/appendices/listings/counts.tex` containing 24
`\newcommand` macros (3 counts × 8 theories) that the appendix captions
reference.

Count predicates (per file, evaluated on the raw lines including
`%`-commented ones — the manually-pruned listings hide most equations
as comments, but the appendix counts should reflect the FULL pipeline
output):

- `EomCount`         — `&=` and `&\supset` markers, minus the Lagrangian
                       and Hamiltonian rows. Counts equations of motion
                       only (not the L definition or the H density).
- `ConstraintCount`  — lines whose stripped math content begins
                       `0 &=` (variants `0 \, &=`, `0&=`, leading
                       whitespace, optional `%` comment prefix all
                       accepted).
- `TermCount`        — ` + ` and ` - ` separators at depth 0 across the
                       whole file. Approximate but consistent.

Idempotent — running with no listing changes produces byte-identical
output.
"""

from __future__ import annotations

import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_LISTINGS_DIR = _REPO_ROOT / "manuscript" / "sections" / "appendices" / "listings"
_SIDECAR = _LISTINGS_DIR / "counts.tex"

# Manifest: listing filename stem → CamelCase macro prefix used in captions.
# The macro names are `\<Prefix>EomCount`, `\<Prefix>ConstraintCount`,
# `\<Prefix>TermCount`.
_MANIFEST: list[tuple[str, str]] = [
    ("baseline", "Baseline"),
    ("euler_heisenberg", "EulerHeisenberg"),
    ("reference", "Reference"),
    ("mechanism", "Mechanism"),
    ("nonminimal", "Nonminimal"),
    ("general_nonminimal", "GeneralNonminimal"),
    ("parity_odd", "ParityOdd"),
    ("dark_photon_plasma", "DarkPhotonPlasma"),
]

# `&=` or `&\supset` — equation marker (Lagrangian, EOM, or Hamiltonian).
# No trailing word boundary: in TeX source `=` is followed by space (a
# non-word character), so `\b` would not match.
_EQ_MARKER = re.compile(r"&(?:=|\\supset)")

# Lagrangian / Hamiltonian markers (to subtract from total to get EOM count).
_LAG_MARKER = re.compile(r"\\mathscr\{L\}\s*&=")
_HAM_MARKER = re.compile(r"\\mathscr\{H\}\s*&(?:=|\\supset)")

# Constraint LHS: `0 &= ...` with the various comment / spacing variants the
# manually-pruned listings use.
_CONSTRAINT_RE = re.compile(r"^\s*%?\s*0\s*(?:\\,)?\s*&=")

# Top-level ` + ` and ` - ` separator (approximate term boundary).
_TERM_SEP = re.compile(r" [+\-] ")


def _counts_for_file(path: Path) -> tuple[int, int, int]:
    text = path.read_text()
    total_eq_markers = len(_EQ_MARKER.findall(text))
    lag = len(_LAG_MARKER.findall(text))
    ham = len(_HAM_MARKER.findall(text))
    eom_count = max(total_eq_markers - lag - ham, 0)

    constraint_count = sum(
        1 for line in text.splitlines() if _CONSTRAINT_RE.search(line)
    )
    term_count = len(_TERM_SEP.findall(text))
    return eom_count, constraint_count, term_count


def main() -> int:
    lines: list[str] = [
        "% Auto-generated by scripts/listings/compute_appendix_counts.py.",
        "% Do not edit by hand. Re-run the script to refresh after listing edits.",
        "%",
        "% Counts are per-theory and reflect the FULL pipeline-emitted system",
        "% (commented-out / pruned equations are counted alongside visible ones).",
        "",
    ]
    for stem, prefix in _MANIFEST:
        path = _LISTINGS_DIR / f"eom_{stem}_full.tex"
        if not path.exists():
            print(f"warning: missing {path.name}; emitting zeros for {prefix}")
            eom, con, term = 0, 0, 0
        else:
            eom, con, term = _counts_for_file(path)
        lines.extend(
            (
                rf"\newcommand{{\{prefix}EomCount}}{{{eom}}}",
                rf"\newcommand{{\{prefix}ConstraintCount}}{{{con}}}",
                rf"\newcommand{{\{prefix}TermCount}}{{{term}}}",
                "",
            )
        )

    output = "\n".join(lines).rstrip() + "\n"
    _SIDECAR.write_text(output)
    print(f"wrote {_SIDECAR.relative_to(_REPO_ROOT)} ({sum(1 for _ in lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
