[theory]
name = "Coupled Scalars"

[spacetime]
dimension = 2
metric = "minkowski"

[[fields]]
name = "phi"
type = "scalar"

[[fields]]
name = "chi"
type = "scalar"

[constants]
names = ["mPhi2", "mChi2", "gCpl"]

[lagrangian]
expression = "-1/2 CD[-a][phi[]] eta[a, b] CD[-b][phi[]] - mPhi2/2 phi[]^2 - 1/2 CD[-a][chi[]] eta[a, b] CD[-b][chi[]] - mChi2/2 chi[]^2 - gCpl phi[] chi[]"

[output]
path = "examples/data/coupled_scalars.json"
