#!/usr/bin/env python3
"""Generate the semantic summary of every committed equation spec.

Corpus-level questions ("how many specs show the #397 signature?", "which
families are grouped from metadata rather than guessed?") were historically
answered by writing a throwaway ``json.load`` scan.  GH #401 records six such
scans, every one of which produced a confident but wrong answer.

This produces the answer once, deterministically, through the vetted accessors
in :mod:`tidal.symbolic.spec_query`, and writes it to a committed text file.
Reading that file replaces writing another scan.  Because it is committed, any
change to derivation or to the semantic layer shows up as a reviewable diff
rather than as silent drift — the #394 failure mode, where a regression went
unnoticed for months because the tests asserted against hand-written fixtures
instead of real pipeline output.

Usage
-----
    python -m scripts.spec_semantics_report            # write the report
    python -m scripts.spec_semantics_report --check    # verify it is current
    python -m scripts.spec_semantics_report --stdout   # print, do not write
"""

from __future__ import annotations

import argparse
import sys
import warnings
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXAMPLES = REPO / "examples" / "data"
GOLDEN = REPO / "tests" / "data" / "spec_semantics.txt"

# Keep the report reproducible: it is diffed byte-for-byte in CI.
_HEADER = (
    "# Semantic summary of examples/data/*.json\n"
    "#\n"
    "# Generated by scripts/spec_semantics_report.py -- do not edit by hand.\n"
    "# Regenerate with:  python -m scripts.spec_semantics_report\n"
    "#\n"
    "# Columns per spec: component families, and any proven sign conflicts.\n"
    "# 'inexact' marks a family grouped by splitting the component name rather\n"
    "# than from exported tensor metadata (specs predating 78374c1).\n"
    "# A conflict is listed only when the opposing sign is PROVEN; pairs the\n"
    "# sign algebra cannot decide are reported as 'undecided' counts, never\n"
    "# guessed at.\n"
)


def _load(path: Path):
    """Load a spec for read-only analysis.

    ``strict_v6=False`` mirrors what ``tidal inspect`` already does on
    read-only paths: analysis never evolves the system, so the higher-time-
    order guard would block inspection of perfectly readable specs.
    """
    from tidal.symbolic.json_loader import load_equation_system

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        return load_equation_system(path, strict_v6=False)


def _describe_spec(path: Path) -> list[str]:
    """Return the report lines for one spec."""
    from tidal.symbolic.spec_query import (
        field_families,
        sibling_sign_conflicts,
    )

    lines = [f"\n## {path.name}"]
    try:
        spec = _load(path)
    except Exception as exc:
        # An unloadable spec is recorded as a status row, never a crash: a
        # corpus tool that dies on one file answers nothing about the rest.
        lines.append(f"  unloadable: {type(exc).__name__}")
        return lines

    for family in field_families(spec):
        marker = "" if family.exact else "  [inexact grouping]"
        slots = family.group_by_temporal_slots()
        slot_text = (
            "  temporal-slots " + ", ".join(f"{k}:{len(v)}" for k, v in slots.items())
            if slots
            else ""
        )
        lines.append(
            f"  family {family.head!r} rank={family.rank} "
            f"n={len(family.members)}{slot_text}{marker}",
        )

    conflicts = sibling_sign_conflicts(spec)
    if conflicts:
        for head, reference, member in conflicts:
            lines.append(
                f"  CONFLICT {head}: {member} opposes {reference} (self laplacian_x)",
            )
    else:
        lines.append("  no proven sign conflicts")
    return lines


def build_report() -> str:
    """Return the full report text for the committed example corpus."""
    lines = [_HEADER.rstrip("\n")]
    paths = sorted(EXAMPLES.glob("*.json"))
    conflicted = 0
    for path in paths:
        spec_lines = _describe_spec(path)
        if any("CONFLICT" in line for line in spec_lines):
            conflicted += 1
        lines.extend(spec_lines)
    lines.extend(
        (
            "\n## summary",
            f"  specs analysed: {len(paths)}",
            f"  specs with a proven sign conflict: {conflicted}",
        )
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write, print, or verify the report.

    Returns
    -------
    int
        ``0`` on success; ``1`` when ``--check`` finds the file out of date.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed report is up to date; do not write",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="print the report instead of writing it",
    )
    args = parser.parse_args(argv)

    report = build_report()

    if args.stdout:
        print(report, end="")
        return 0

    if args.check:
        if not GOLDEN.exists():
            print(f"missing {GOLDEN}; run: python -m scripts.spec_semantics_report")
            return 1
        if GOLDEN.read_text() != report:
            print(
                f"{GOLDEN} is out of date.\n"
                "Regenerate with: python -m scripts.spec_semantics_report",
            )
            return 1
        print(f"{GOLDEN} is up to date")
        return 0

    GOLDEN.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN.write_text(report)
    print(f"wrote {GOLDEN}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
