[theory]
name = "Klein-Gordon 3D"

[spacetime]
dimension = 4
metric = "minkowski"

[[fields]]
name = "phi"
type = "scalar"

[constants]
names = ["m2"]

[lagrangian]
expression = "-1/2 CD[-a][phi[]] eta[a, b] CD[-b][phi[]] - m2/2 phi[]^2"

[parameters]
m2 = 1.0

[output]
path = "../data/klein_gordon_3d.json"
